### ISSUE TITLE
question about your downloader

### ISSUE THREAD

**Issue by ghost** [dgbrewer1989/MangaDownloader#1]
As far as I understand, it downloads the manga added via "add manga" and if there are new chapters when we run it as a cron job, it downloads them right?

**Comment by dgbrewer1989** [comment]
This was already closed but to give some insight: The main application itself will read the json file and check for updates based on those records. The cron job itself is a separate setup. I didn't know if it would be best to add it into the main application or not, so I opted not to. Seems like it might be a good idea though.
