### ISSUE TITLE
it asks language on mangadex even though already selected

### ISSUE THREAD

**Issue by ghost** [dgbrewer1989/MangaDownloader#2]
![2023-09-17-115459_1920x1080_scrot](https://github.com/dgbrewer1989/MangaDownloader/assets/43301560/ed79a86e-7612-45ce-bea5-08ecdd7ff627)
url https://mangadex.org/title/706a3219-646d-4fdd-833c-234ca616029e/tedama-ni-toritai-kurokiya-san
```[{"name": "Can I live With You?", "url": "https://mangadex.org/title/4509fd84-c003-4c57-ab07-e207e6999dab/can-i-live-with-you"}, {"name": "", "url": "https://mangadex.org/title/706a3219-646d-4fdd-833c-234ca616029e/tedama-ni-toritai-kurokiya-san"}]```

**Comment by ghost** [comment]
fixed it via --arguments language=en

**Comment by dgbrewer1989** [comment]
I just realized that was happening with MangaDex links. Haven't used MangaDex links until now so probably needs an update somewhere to note that in these docs or in Manga-Py.
